# device: "cuda" | "cpu"
device: cuda
seed: 309

# distributed settings
rounds: 50
total_users: 31
num_attackers: 14
part_rate: 1
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.5/user_dataidx_map_0.50_0.dat"
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.1/user_dataidx_map_0.10_0.dat"

# attacker model 
attacker_model: "signflipping"
# attacker_model: "omniscient_signflipping"
attacker_model: "fang"

# hyperparameters and settings
aggregator: "mean"
aggregator: "krum"
input_b: 5
multimkrum_param: 15
# aggregator: "median"


batch_size: 100
tau: 20
optimizer: "Adam"
lr: 5.e-3
momentum: 0
weight_decay: 5.e-4

model: "lenet_5"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "fmnist"
data_path: "/mnt/ex-ssd/Datasets/fmnist/"
# dataset: "cifar10"
# data_path: "/mnt/ex-ssd/Datasets/cifar10/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
