# device: "cuda" | "cpu"
device: cuda
seed: 1002

# distributed settings
rounds: 50
total_users: 31
num_attackers: 2
part_rate: 1
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.5/user_dataidx_map_0.50_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.2/user_dataidx_map_0.2_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.05/user_dataidx_map_0.05_0.dat"
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/iid/iid_mapping_0.dat"
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.1/user_dataidx_map_0.10_0.dat"

# attacker model 
attacker_model: "signflipping"
# attacker_model: "omniscient_signflipping"
attacker_model: "fang"
# attacker_model: "ipm"
# ipm_multiplier: 1.3
# attacker_model: "alie"
# attacker_model: "model_replace"
# # model_checkpoint: "/home/kyue/expdata/byzantine/a0.1/signflipping/krum/6/checkpoint.pth"
# # model_checkpoint: "/home/kyue/expdata/byzantine/mr_models/0719_2303/checkpoint.pth"
# attacker_model: "omniscient_trapsetter"
# attacker_model: "nonomniscient_trapsetter"
# model_checkpoint: ""
# scaling_factor: 0.1
# radius: 0.5

# compressor
compressor: "none"

# hyperparameters and settings
aggregator: "mean"
# aggregator: "krum"
input_b: 14
multimkrum_param: 14
# aggregator: "median"
# aggregator: "trimmed_mean"
aggregator: "centeredclipping"
cc_bound: 10

store_momentum: True

# aggregator: "vote"
global_lr: 1.

batch_size: 100
tau: 20
optimizer: "Adam"
lr: 5.e-4
weight_decay: 5.e-4

model: "lenet_5"
checkpoint_path: ""
# checkpoint_path: "/home/kyue/expdata/byzantine/mr_models/0719_2303/checkpoint.pth"

# Simulation dataset configurations
dataset: "fmnist"
data_path: "/mnt/ex-ssd/Datasets/fmnist/"
# dataset: "cifar10"
# data_path: "/mnt/ex-ssd/Datasets/cifar10/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
