# device: "cuda" | "cpu"
device: cuda
seed: 1002

# distributed settings
rounds: 50
total_users: 31
num_attackers: 10
part_rate: 1
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.5/user_dataidx_map_0.50_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.2/user_dataidx_map_0.2_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.05/user_dataidx_map_0.05_0.dat"
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/iid/iid_mapping_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.1/user_dataidx_map_0.10_0.dat"

# attacker model 
attacker_model: "rop"
PI: 120
rop_scaling_factor: 100

# compressor
compressor: "none"

# hyperparameters and settings
aggregator: "mean"
# aggregator: "krum"
input_b: 14
multimkrum_param: 14
# aggregator: "median"
# aggregator: "trimmed_mean"
# aggregator: "centeredclipping"
cc_bound: 10
store_momentum: True

# aggregator: "vote"
# global_lr: 1.e-3

batch_size: 100
tau: 20
optimizer: "Adam"
lr: 5.e-4
weight_decay: 5.e-4

model: "lenet_5"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "fmnist"
data_path: "/mnt/ex-ssd/Datasets/fmnist/"
# dataset: "cifar10"
# data_path: "/mnt/ex-ssd/Datasets/cifar10/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"

# DDP setup
ddp: True
ddp: False
bound: 1.e-6
std: 0.

# local dp setup
ldp: True
ldp: False
local_bound: 1.
local_std: 10