# device: "cuda" | "cpu"
device: cuda
seed: 1002

# distributed settings
rounds: 100
total_users: 31
num_attackers: 2
part_rate: 1
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.5/user_dataidx_map_0.50_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.2/user_dataidx_map_0.2_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.05/user_dataidx_map_0.05_0.dat"
user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/iid/iid_mapping_0.dat"
# user_data_mapping: "/mnt/ex-ssd/Datasets/user_with_data/fmnist/a0.1/user_dataidx_map_0.10_0.dat"

# attacker model 
attacker_model: "signflipping"
# attacker_model: "omniscient_signflipping"
# attacker_model: "fang"
# attacker_model: "ipm"
# ipm_multiplier: 1.1
attacker_model: "alie"
attacker_model: "nonomniscient_trapsetter"
model_checkpoint: ""
scaling_factor: 0.1
radius: 0.5

# compressor
compressor: "optim_sto_signSGD"
# compressor: "none"

# hyperparameters and settings
aggregator: "vote"
global_lr: 5.e-4
store_momentum: False

batch_size: 100
tau: 1
optimizer: "Adam"
lr: 1.e-3

# tau: 1
# optimizer: "SGD"
# nesterov: False
# lr: 1.e-4
# momentum: 0.9

weight_decay: 5.e-4

model: "lenet_5"
checkpoint_path: ""

# Simulation dataset configurations
dataset: "fmnist"
data_path: "/mnt/ex-ssd/Datasets/fmnist/"
# dataset: "cifar10"
# data_path: "/mnt/ex-ssd/Datasets/cifar10/"

# Log configurations
output_folder: "experiments"
test_interval: 1
print_every:   20
log_level:   "INFO"
log_file:    "./train.log"
